version: '3.9'

services:
  app:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - '4040:4040'
    depends_on:
      - postgres
    restart: always
    env_file:
      - ./backend/.env
  
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stairwaytoheaven
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

networks:
  default:
    driver: bridge
