version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '4040:4040'
    depends_on:
      - postgres
    env_file:
      - ./.env
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stairwaytoheaven
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

networks:
  default:
    driver: bridge
